# Generated by Django 5.1.1 on 2024-09-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PongCustomGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_ball', models.JSONField(blank=True, null=True)),
                ('custom_plateau', models.JSONField(blank=True, null=True)),
                ('custom_paddle', models.JSONField(blank=True, null=True)),
                ('custom_map', models.JSONField(blank=True, null=True)),
                ('custom_score', models.JSONField(blank=True, null=True)),
                ('custom_animation', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
