# Generated by Django 5.1.1 on 2024-09-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_game_tournament_next_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_tournament',
            name='layer',
            field=models.IntegerField(default=0),
        ),
    ]
