# Generated by Django 5.1.1 on 2024-09-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pongcustomgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pongcustomgame',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
