# Generated by Django 5.1.1 on 2024-09-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_game_tournament_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='name',
            field=models.CharField(default='Lobby', max_length=255),
        ),
    ]
