# Generated by Django 5.1 on 2024-09-02 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_game_id_remove_player_elo_game_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinvitation',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='api.game'),
        ),
    ]
