# Generated by Django 5.1.1 on 2024-09-22 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_pongcustomgame_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='custom_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pongcustomgame'),
        ),
        migrations.AddField(
            model_name='game_tournament',
            name='custom_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pongcustomgame'),
        ),
    ]
