# Generated by Django 5.1.1 on 2024-09-11 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_lobby_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='api.player'),
        ),
    ]
