# Generated by Django 5.0.7 on 2024-07-27 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameinvitation',
            name='game_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='api.game'),
        ),
    ]
