# Generated by Django 5.0.6 on 2024-06-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_delete_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.CharField(default='', max_length=255),
        ),
    ]
