# Generated by Django 5.0.6 on 2024-06-24 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_nickname_user_mail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Player',
        ),
    ]
