# Generated by Django 5.0.6 on 2024-06-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_user_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='elo',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
