# Generated by Django 5.0.6 on 2024-07-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='mail',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
