# Generated by Django 5.0.6 on 2024-07-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_player_mail_alter_player_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='img',
            field=models.ImageField(default='profile_images/default.png', upload_to='profile_images/'),
        ),
    ]
