# Generated by Django 5.0.6 on 2024-07-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_player_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='img',
            field=models.CharField(default='/img.png', max_length=255),
        ),
    ]
