# Generated by Django 5.0.6 on 2024-07-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_player_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
