# Generated by Django 3.2.25 on 2024-07-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_player_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='img',
            field=models.ImageField(default='/media/profile_pics/default.png', upload_to='profile_pics'),
        ),
    ]
